name: Testing workflow

on:
  push:
  pull_request:
    branches: [ master ]
    types: [ labeled ]

  workflow_dispatch:

jobs:
  sanity_check:
    # if: ${{ github.event.label.name == 'integration' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check PR content
        run: echo PR content is valid

  stage_1:
    needs: sanity_check
    runs-on: ubuntu-latest
    steps:
      - name: clone central repo and submodules
        uses: actions/checkout@v2
        with:
          repository: central-organization/master_repo
          ref: master

      - name: Update each submodule's head
        run: git submodule update --init --recursive

      - name: run LS
        run: ls

      - name: set env variables
        run: echo set env variables

      - name: check python version
        run: python --version | grep "3.8.10" || exit 1

      - name: install requirements
        run: |
          cd ci_repo/Tools/test_framework
          pip install -r requirements.txt

      - name: download package archive
        run: echo download

      - name: unzip package archive
        run: echo unzip

      - name: run Stage-1 tests
        run: echo run stage-1

      - name: check if all tests passed
        run: echo check

      - name: archive and upload logs
        run: echo logs upload
