name: Testing workflow

on:
  # push:
  pull_request:
    branches: [ master ]
    types: [ labeled ]

jobs:
  sanity_check:
    # if: ${{ github.event.label.name == 'integration' }}
    runs-on: ubuntu-latest
    steps:
      # - name: clone master repo and submodules
      #   uses: central-organization/ci_repo/.github/actions/checkout_repo_with_submodules@master
      #   with:
      #     fetch-depth: 0
      #     repo: central-organization/master_repo
      #     ref: master
      #     token: ${{ secrets.SUPER_TOKEN }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: central-organization/master_repo
          token: ${{ secrets.SUPER_TOKEN }}
      - run: git submodule update --init --remote --recursive
        shell: bash

      - name: git diff
        run: |
          cd $(pwd)/Provider_submodules/provider_name_repo
          ls
          git diff origin/master origin/${{ github.event.pull_request.head.ref }}

      - name: print github.event.pull_request.base.sha
        run: echo ${{ github.event.pull_request.base.sha }}

      - name: print github.sha
        run: echo $ {{ github.sha }}

      - name: ls pwd
        run: ls $(pwd)

      - name: print pwd
        run: pwd

      - name: check PR content
        run: |
          pwd
          ls $(pwd)/Provider_submodules/provider_name_repo
          python ci_repo/Scripts/validate_pr_diff.py --git_repo_path $(pwd)/Provider_submodules/provider_name_repo --pr_base_sha origin/master --pr_head_sha origin/${{ github.event.pull_request.head.ref }}

  stage_1:
    needs: sanity_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set env variables
        run: echo set env variables

      - name: check python version
        run: python --version

      - name: install requirements
        run: echo requirements

      - name: download package archive
        run: echo download

      - name: unzip package archive
        run: echo unzip

      - name: run Stage-1 tests
        run: echo run stage-1

      - name: check if all tests passed
        run: echo check

      - name: archive and upload logs
        run: echo logs upload
