name: Testing workflow

on:
  # push:
  pull_request:
    branches: [ master ]
    types: [ labeled ]

jobs:
  sanity_check:
    # if: ${{ github.event.label.name == 'integration' }}
    runs-on: ubuntu-latest
    steps:
      - name: clone central repo and submodules
        uses: actions/checkout@v2
        with:
          repository: central-organization/master_repo
          ref: master

      - name: check PR content
        run: |
          pwd
          python ci_repo/Scripts/validate_pr_diff.py --pr_base_sha ${{ github.event.pull_request.base.sha }} --pr_head_sha ${{ github.sha }}

  stage_1:
    needs: sanity_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set env variables
        run: echo set env variables

      - name: check python version
        run: python --version

      - name: install requirements
        run: echo requirements

      - name: download package archive
        run: echo download

      - name: unzip package archive
        run: echo unzip

      - name: run Stage-1 tests
        run: echo run stage-1

      - name: check if all tests passed
        run: echo check

      - name: archive and upload logs
        run: echo logs upload
