name: Update submodules

on:
  push:
    branches: [  update_master_repo_bot  ]

  workflow_dispatch:


jobs:
  call-workflow-passing-data:
    uses: central-organization/ci_repo/.github/workflows/update_submodules_bot.yml@update-submodule
    secrets:
      token: ${{ secrets.SUPER_TOKEN }}
