name: Bot

on:
  push:
    branches: [  update_master_repo_bot  ]

  workflow_dispatch:


jobs:
  call-workflow-passing-data:
    uses: central-organization/ci_repo/.github/workflows/hello_world.yml@test-branch
    with:
    secrets:
      token: ${{ secrets.SUPER_TOKEN }}
